# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[(b'android', b'android'), (b'ios', b'ios'), (b'firefox', b'firefox'), (b'chrome', b'chrome')], max_length=20),
        ),
    ]
